apiVersion: v1
kind: Service
metadata:
  name: traffic-analyzer-server
spec:
  selector:
    app: traffic-analyzer-server
  ports:
    - name: grpc
      port: {{ .Values.server.ports.grpc }}
      targetPort: {{ .Values.server.ports.grpc }}
    - name: http
      port: {{ .Values.server.ports.http }}
      targetPort: {{ .Values.server.ports.http }}
