// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packet_event.proto

#include "packet_event.pb.h"
#include "packet_event.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace traffic {

static const char* PacketIngest_method_names[] = {
  "/traffic.PacketIngest/StreamPackets",
};

std::unique_ptr< PacketIngest::Stub> PacketIngest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PacketIngest::Stub> stub(new PacketIngest::Stub(channel, options));
  return stub;
}

PacketIngest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamPackets_(PacketIngest_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::traffic::IngestMessage>* PacketIngest::Stub::StreamPacketsRaw(::grpc::ClientContext* context, ::traffic::IngestSummary* response) {
  return ::grpc::internal::ClientWriterFactory< ::traffic::IngestMessage>::Create(channel_.get(), rpcmethod_StreamPackets_, context, response);
}

void PacketIngest::Stub::async::StreamPackets(::grpc::ClientContext* context, ::traffic::IngestSummary* response, ::grpc::ClientWriteReactor< ::traffic::IngestMessage>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::traffic::IngestMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamPackets_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::traffic::IngestMessage>* PacketIngest::Stub::AsyncStreamPacketsRaw(::grpc::ClientContext* context, ::traffic::IngestSummary* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::traffic::IngestMessage>::Create(channel_.get(), cq, rpcmethod_StreamPackets_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::traffic::IngestMessage>* PacketIngest::Stub::PrepareAsyncStreamPacketsRaw(::grpc::ClientContext* context, ::traffic::IngestSummary* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::traffic::IngestMessage>::Create(channel_.get(), cq, rpcmethod_StreamPackets_, context, response, false, nullptr);
}

PacketIngest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PacketIngest_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< PacketIngest::Service, ::traffic::IngestMessage, ::traffic::IngestSummary>(
          [](PacketIngest::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::traffic::IngestMessage>* reader,
             ::traffic::IngestSummary* resp) {
               return service->StreamPackets(ctx, reader, resp);
             }, this)));
}

PacketIngest::Service::~Service() {
}

::grpc::Status PacketIngest::Service::StreamPackets(::grpc::ServerContext* context, ::grpc::ServerReader< ::traffic::IngestMessage>* reader, ::traffic::IngestSummary* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace traffic
#include <grpcpp/ports_undef.inc>

