// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_event.proto
// Protobuf C++ Version: 7.35.1

#ifndef packet_5fevent_2eproto_2epb_2eh
#define packet_5fevent_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packet_5fevent_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_5fevent_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_packet_5fevent_2eproto;
}  // extern "C"
namespace traffic {
class IngestMessage;
struct IngestMessageGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern IngestMessageGlobalsTypeInternal IngestMessage_globals_;
extern const ::google::protobuf::internal::ClassDataFull IngestMessage_class_data_;
#else
extern const IngestMessageGlobalsTypeInternal IngestMessage_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class IngestSummary;
struct IngestSummaryGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern IngestSummaryGlobalsTypeInternal IngestSummary_globals_;
extern const ::google::protobuf::internal::ClassDataFull IngestSummary_class_data_;
#else
extern const IngestSummaryGlobalsTypeInternal IngestSummary_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PacketEvent;
struct PacketEventGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PacketEventGlobalsTypeInternal PacketEvent_globals_;
extern const ::google::protobuf::internal::ClassDataFull PacketEvent_class_data_;
#else
extern const PacketEventGlobalsTypeInternal PacketEvent_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class SessionInfo;
struct SessionInfoGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SessionInfoGlobalsTypeInternal SessionInfo_globals_;
extern const ::google::protobuf::internal::ClassDataFull SessionInfo_class_data_;
#else
extern const SessionInfoGlobalsTypeInternal SessionInfo_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace traffic
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace traffic {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SessionInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:traffic.SessionInfo) */ {
 public:
  inline SessionInfo() : SessionInfo(nullptr) {}
  ~SessionInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SessionInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SessionInfo));
  }
#endif

  template <typename = void>
  explicit constexpr SessionInfo(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SessionInfo(const SessionInfo& from) : SessionInfo(nullptr, from) {}
  inline SessionInfo(SessionInfo&& from) noexcept : SessionInfo(nullptr, ::std::move(from)) {}
  inline SessionInfo& operator=(const SessionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionInfo& operator=(SessionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const SessionInfo& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SessionInfo>(&SessionInfo_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SessionInfo& a, SessionInfo& b) { a.Swap(&b); }
  inline void Swap(SessionInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SessionInfo* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SessionInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SessionInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SessionInfo& from) { SessionInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SessionInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "traffic.SessionInfo"; }

  explicit SessionInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SessionInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SessionInfo& from);
  SessionInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SessionInfo&& from) noexcept
      : SessionInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kInterfaceNameFieldNumber = 2,
    kStartedUnixMsFieldNumber = 3,
  };
  // string session_id = 1;
  void clear_session_id() ;
  [[nodiscard]] const ::std::string& session_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_id();
  void set_allocated_session_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_id();

  public:
  // string interface_name = 2;
  void clear_interface_name() ;
  [[nodiscard]] const ::std::string& interface_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_interface_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_interface_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_interface_name();
  void set_allocated_interface_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_interface_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_interface_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_interface_name();

  public:
  // int64 started_unix_ms = 3;
  void clear_started_unix_ms() ;
  [[nodiscard]] ::int64_t started_unix_ms() const;
  void set_started_unix_ms(::int64_t value);

  private:
  ::int64_t _internal_started_unix_ms() const;
  void _internal_set_started_unix_ms(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:traffic.SessionInfo)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 3,
                          0, 52,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SessionInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_id_;
    ::google::protobuf::internal::ArenaStringPtr interface_name_;
    ::int64_t started_unix_ms_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fevent_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PacketEvent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:traffic.PacketEvent) */ {
 public:
  inline PacketEvent() : PacketEvent(nullptr) {}
  ~PacketEvent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PacketEvent* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PacketEvent));
  }
#endif

  template <typename = void>
  explicit constexpr PacketEvent(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PacketEvent(const PacketEvent& from) : PacketEvent(nullptr, from) {}
  inline PacketEvent(PacketEvent&& from) noexcept : PacketEvent(nullptr, ::std::move(from)) {}
  inline PacketEvent& operator=(const PacketEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketEvent& operator=(PacketEvent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PacketEvent& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PacketEvent>(&PacketEvent_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PacketEvent& a, PacketEvent& b) { a.Swap(&b); }
  inline void Swap(PacketEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketEvent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PacketEvent* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PacketEvent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PacketEvent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PacketEvent& from) { PacketEvent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PacketEvent* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "traffic.PacketEvent"; }

  explicit PacketEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PacketEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PacketEvent& from);
  PacketEvent(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PacketEvent&& from) noexcept
      : PacketEvent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAlertsFieldNumber = 9,
    kSourceIpFieldNumber = 1,
    kDestIpFieldNumber = 2,
    kProtocolFieldNumber = 5,
    kTcpFlagsFieldNumber = 7,
    kSourcePortFieldNumber = 3,
    kDestPortFieldNumber = 4,
    kTimestampUnixMsFieldNumber = 8,
    kLengthBytesFieldNumber = 6,
  };
  // repeated string alerts = 9;
  [[nodiscard]] int alerts_size()
      const;
  private:
  int _internal_alerts_size() const;

  public:
  void clear_alerts() ;
  [[nodiscard]] const ::std::string& alerts(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_alerts(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_alerts(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_alerts();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_alerts(Arg_&& value, Args_... args);
  [[nodiscard]] const
      ::google::protobuf::RepeatedPtrField<::std::string>&
      alerts() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::std::string>*
      PROTOBUF_NONNULL
      mutable_alerts();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_alerts() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_alerts();

  public:
  // string source_ip = 1;
  void clear_source_ip() ;
  [[nodiscard]] const ::std::string& source_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_source_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_source_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_source_ip();
  void set_allocated_source_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_source_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_source_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_source_ip();

  public:
  // string dest_ip = 2;
  void clear_dest_ip() ;
  [[nodiscard]] const ::std::string& dest_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dest_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dest_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dest_ip();
  void set_allocated_dest_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dest_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dest_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dest_ip();

  public:
  // string protocol = 5;
  void clear_protocol() ;
  [[nodiscard]] const ::std::string& protocol() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_protocol(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_protocol();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_protocol();
  void set_allocated_protocol(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_protocol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_protocol(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_protocol();

  public:
  // string tcp_flags = 7;
  void clear_tcp_flags() ;
  [[nodiscard]] const ::std::string& tcp_flags() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tcp_flags(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tcp_flags();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tcp_flags();
  void set_allocated_tcp_flags(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tcp_flags() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tcp_flags(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tcp_flags();

  public:
  // uint32 source_port = 3;
  void clear_source_port() ;
  [[nodiscard]] ::uint32_t source_port() const;
  void set_source_port(::uint32_t value);

  private:
  ::uint32_t _internal_source_port() const;
  void _internal_set_source_port(::uint32_t value);

  public:
  // uint32 dest_port = 4;
  void clear_dest_port() ;
  [[nodiscard]] ::uint32_t dest_port() const;
  void set_dest_port(::uint32_t value);

  private:
  ::uint32_t _internal_dest_port() const;
  void _internal_set_dest_port(::uint32_t value);

  public:
  // int64 timestamp_unix_ms = 8;
  void clear_timestamp_unix_ms() ;
  [[nodiscard]] ::int64_t timestamp_unix_ms() const;
  void set_timestamp_unix_ms(::int64_t value);

  private:
  ::int64_t _internal_timestamp_unix_ms() const;
  void _internal_set_timestamp_unix_ms(::int64_t value);

  public:
  // uint32 length_bytes = 6;
  void clear_length_bytes() ;
  [[nodiscard]] ::uint32_t length_bytes() const;
  void set_length_bytes(::uint32_t value);

  private:
  ::uint32_t _internal_length_bytes() const;
  void _internal_set_length_bytes(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:traffic.PacketEvent)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<4, 9,
                          0, 75,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PacketEvent& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> alerts_;
    ::google::protobuf::internal::ArenaStringPtr source_ip_;
    ::google::protobuf::internal::ArenaStringPtr dest_ip_;
    ::google::protobuf::internal::ArenaStringPtr protocol_;
    ::google::protobuf::internal::ArenaStringPtr tcp_flags_;
    ::uint32_t source_port_;
    ::uint32_t dest_port_;
    ::int64_t timestamp_unix_ms_;
    ::uint32_t length_bytes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fevent_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED IngestSummary final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:traffic.IngestSummary) */ {
 public:
  inline IngestSummary() : IngestSummary(nullptr) {}
  ~IngestSummary() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IngestSummary* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IngestSummary));
  }
#endif

  template <typename = void>
  explicit constexpr IngestSummary(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline IngestSummary(const IngestSummary& from) : IngestSummary(nullptr, from) {}
  inline IngestSummary(IngestSummary&& from) noexcept : IngestSummary(nullptr, ::std::move(from)) {}
  inline IngestSummary& operator=(const IngestSummary& from) {
    CopyFrom(from);
    return *this;
  }
  inline IngestSummary& operator=(IngestSummary&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const IngestSummary& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<IngestSummary>(&IngestSummary_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(IngestSummary& a, IngestSummary& b) { a.Swap(&b); }
  inline void Swap(IngestSummary* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IngestSummary* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] IngestSummary* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IngestSummary>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IngestSummary& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IngestSummary& from) { IngestSummary::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IngestSummary* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "traffic.IngestSummary"; }

  explicit IngestSummary(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IngestSummary(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IngestSummary& from);
  IngestSummary(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IngestSummary&& from) noexcept
      : IngestSummary(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPacketsReceivedFieldNumber = 1,
    kAlertsReceivedFieldNumber = 2,
  };
  // int64 packets_received = 1;
  void clear_packets_received() ;
  [[nodiscard]] ::int64_t packets_received() const;
  void set_packets_received(::int64_t value);

  private:
  ::int64_t _internal_packets_received() const;
  void _internal_set_packets_received(::int64_t value);

  public:
  // int64 alerts_received = 2;
  void clear_alerts_received() ;
  [[nodiscard]] ::int64_t alerts_received() const;
  void set_alerts_received(::int64_t value);

  private:
  ::int64_t _internal_alerts_received() const;
  void _internal_set_alerts_received(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:traffic.IngestSummary)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IngestSummary& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t packets_received_;
    ::int64_t alerts_received_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fevent_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED IngestMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:traffic.IngestMessage) */ {
 public:
  inline IngestMessage() : IngestMessage(nullptr) {}
  ~IngestMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IngestMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IngestMessage));
  }
#endif

  template <typename = void>
  explicit constexpr IngestMessage(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline IngestMessage(const IngestMessage& from) : IngestMessage(nullptr, from) {}
  inline IngestMessage(IngestMessage&& from) noexcept : IngestMessage(nullptr, ::std::move(from)) {}
  inline IngestMessage& operator=(const IngestMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline IngestMessage& operator=(IngestMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const IngestMessage& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<IngestMessage>(&IngestMessage_globals_);
  }
  enum PayloadCase {
    kSessionInfo = 1,
    kPacketEvent = 2,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(IngestMessage& a, IngestMessage& b) { a.Swap(&b); }
  inline void Swap(IngestMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IngestMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] IngestMessage* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IngestMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IngestMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IngestMessage& from) { IngestMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IngestMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "traffic.IngestMessage"; }

  explicit IngestMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IngestMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IngestMessage& from);
  IngestMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IngestMessage&& from) noexcept
      : IngestMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionInfoFieldNumber = 1,
    kPacketEventFieldNumber = 2,
  };
  // .traffic.SessionInfo session_info = 1;
  [[nodiscard]] bool has_session_info()
      const;
  private:
  bool _internal_has_session_info() const;

  public:
  void clear_session_info() ;
  [[nodiscard]] const ::traffic::SessionInfo& session_info() const;
  [[nodiscard]] ::traffic::SessionInfo* PROTOBUF_NULLABLE release_session_info();
  ::traffic::SessionInfo* PROTOBUF_NONNULL mutable_session_info();
  void set_allocated_session_info(::traffic::SessionInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_session_info(::traffic::SessionInfo* PROTOBUF_NULLABLE value);
  ::traffic::SessionInfo* PROTOBUF_NULLABLE unsafe_arena_release_session_info();

  private:
  const ::traffic::SessionInfo& _internal_session_info() const;
  ::traffic::SessionInfo* PROTOBUF_NONNULL _internal_mutable_session_info();

  public:
  // .traffic.PacketEvent packet_event = 2;
  [[nodiscard]] bool has_packet_event()
      const;
  private:
  bool _internal_has_packet_event() const;

  public:
  void clear_packet_event() ;
  [[nodiscard]] const ::traffic::PacketEvent& packet_event() const;
  [[nodiscard]] ::traffic::PacketEvent* PROTOBUF_NULLABLE release_packet_event();
  ::traffic::PacketEvent* PROTOBUF_NONNULL mutable_packet_event();
  void set_allocated_packet_event(::traffic::PacketEvent* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_packet_event(::traffic::PacketEvent* PROTOBUF_NULLABLE value);
  ::traffic::PacketEvent* PROTOBUF_NULLABLE unsafe_arena_release_packet_event();

  private:
  const ::traffic::PacketEvent& _internal_packet_event() const;
  ::traffic::PacketEvent* PROTOBUF_NONNULL _internal_mutable_packet_event();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:traffic.IngestMessage)
 private:
  class _Internal;
  void set_has_session_info();
  void set_has_packet_event();
  [[nodiscard]] inline bool has_payload() const;
  inline void clear_has_payload();
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 2,
                          2, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IngestMessage& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::traffic::SessionInfo* PROTOBUF_NULLABLE session_info_;
      ::traffic::PacketEvent* PROTOBUF_NULLABLE packet_event_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fevent_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PacketEvent

// string source_ip = 1;
inline void PacketEvent::clear_source_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& PacketEvent::source_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.source_ip)
  return _internal_source_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PacketEvent::set_source_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.source_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.source_ip)
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::mutable_source_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_source_ip();
  // @@protoc_insertion_point(field_mutable:traffic.PacketEvent.source_ip)
  return _s;
}
inline const ::std::string& PacketEvent::_internal_source_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_ip_.Get();
}
inline void PacketEvent::_internal_set_source_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::_internal_mutable_source_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PacketEvent::release_source_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic.PacketEvent.source_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.source_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_ip_.Set("", GetArena());
  }
  return released;
}
inline void PacketEvent::set_allocated_source_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.source_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_ip_.IsDefault()) {
    _impl_.source_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic.PacketEvent.source_ip)
}

// string dest_ip = 2;
inline void PacketEvent::clear_dest_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& PacketEvent::dest_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.dest_ip)
  return _internal_dest_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PacketEvent::set_dest_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.dest_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.dest_ip)
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::mutable_dest_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_dest_ip();
  // @@protoc_insertion_point(field_mutable:traffic.PacketEvent.dest_ip)
  return _s;
}
inline const ::std::string& PacketEvent::_internal_dest_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_ip_.Get();
}
inline void PacketEvent::_internal_set_dest_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::_internal_mutable_dest_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dest_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PacketEvent::release_dest_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic.PacketEvent.dest_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.dest_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dest_ip_.Set("", GetArena());
  }
  return released;
}
inline void PacketEvent::set_allocated_dest_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.dest_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dest_ip_.IsDefault()) {
    _impl_.dest_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic.PacketEvent.dest_ip)
}

// uint32 source_port = 3;
inline void PacketEvent::clear_source_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_port_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::uint32_t PacketEvent::source_port() const {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.source_port)
  return _internal_source_port();
}
inline void PacketEvent::set_source_port(::uint32_t value) {
  _internal_set_source_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.source_port)
}
inline ::uint32_t PacketEvent::_internal_source_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_port_;
}
inline void PacketEvent::_internal_set_source_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_port_ = value;
}

// uint32 dest_port = 4;
inline void PacketEvent::clear_dest_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_port_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::uint32_t PacketEvent::dest_port() const {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.dest_port)
  return _internal_dest_port();
}
inline void PacketEvent::set_dest_port(::uint32_t value) {
  _internal_set_dest_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.dest_port)
}
inline ::uint32_t PacketEvent::_internal_dest_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dest_port_;
}
inline void PacketEvent::_internal_set_dest_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dest_port_ = value;
}

// string protocol = 5;
inline void PacketEvent::clear_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& PacketEvent::protocol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.protocol)
  return _internal_protocol();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PacketEvent::set_protocol(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.protocol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.protocol)
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::mutable_protocol()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_protocol();
  // @@protoc_insertion_point(field_mutable:traffic.PacketEvent.protocol)
  return _s;
}
inline const ::std::string& PacketEvent::_internal_protocol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.protocol_.Get();
}
inline void PacketEvent::_internal_set_protocol(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::_internal_mutable_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.protocol_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PacketEvent::release_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic.PacketEvent.protocol)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.protocol_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.protocol_.Set("", GetArena());
  }
  return released;
}
inline void PacketEvent::set_allocated_protocol(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.protocol_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic.PacketEvent.protocol)
}

// uint32 length_bytes = 6;
inline void PacketEvent::clear_length_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_bytes_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline ::uint32_t PacketEvent::length_bytes() const {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.length_bytes)
  return _internal_length_bytes();
}
inline void PacketEvent::set_length_bytes(::uint32_t value) {
  _internal_set_length_bytes(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.length_bytes)
}
inline ::uint32_t PacketEvent::_internal_length_bytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.length_bytes_;
}
inline void PacketEvent::_internal_set_length_bytes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_bytes_ = value;
}

// string tcp_flags = 7;
inline void PacketEvent::clear_tcp_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tcp_flags_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline const ::std::string& PacketEvent::tcp_flags() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.tcp_flags)
  return _internal_tcp_flags();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PacketEvent::set_tcp_flags(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.tcp_flags_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.tcp_flags)
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::mutable_tcp_flags()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_tcp_flags();
  // @@protoc_insertion_point(field_mutable:traffic.PacketEvent.tcp_flags)
  return _s;
}
inline const ::std::string& PacketEvent::_internal_tcp_flags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tcp_flags_.Get();
}
inline void PacketEvent::_internal_set_tcp_flags(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tcp_flags_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::_internal_mutable_tcp_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tcp_flags_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PacketEvent::release_tcp_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic.PacketEvent.tcp_flags)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.tcp_flags_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tcp_flags_.Set("", GetArena());
  }
  return released;
}
inline void PacketEvent::set_allocated_tcp_flags(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.tcp_flags_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tcp_flags_.IsDefault()) {
    _impl_.tcp_flags_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic.PacketEvent.tcp_flags)
}

// int64 timestamp_unix_ms = 8;
inline void PacketEvent::clear_timestamp_unix_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_unix_ms_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::int64_t PacketEvent::timestamp_unix_ms() const {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.timestamp_unix_ms)
  return _internal_timestamp_unix_ms();
}
inline void PacketEvent::set_timestamp_unix_ms(::int64_t value) {
  _internal_set_timestamp_unix_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.timestamp_unix_ms)
}
inline ::int64_t PacketEvent::_internal_timestamp_unix_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_unix_ms_;
}
inline void PacketEvent::_internal_set_timestamp_unix_ms(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_unix_ms_ = value;
}

// repeated string alerts = 9;
inline int PacketEvent::_internal_alerts_size() const {
  return _internal_alerts().size();
}
inline int PacketEvent::alerts_size() const {
  return _internal_alerts_size();
}
inline void PacketEvent::clear_alerts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alerts_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::add_alerts()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_alerts()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:traffic.PacketEvent.alerts)
  return _s;
}
inline const ::std::string& PacketEvent::alerts(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.PacketEvent.alerts)
  return _internal_alerts().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL PacketEvent::mutable_alerts(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:traffic.PacketEvent.alerts)
  return _internal_mutable_alerts()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void PacketEvent::set_alerts(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_alerts()->Mutable(index),
      ::std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:traffic.PacketEvent.alerts)
}
template <typename Arg_, typename... Args_>
inline void PacketEvent::add_alerts(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_alerts(), ::std::forward<Arg_>(value),
      args... );
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:traffic.PacketEvent.alerts)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& PacketEvent::alerts()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:traffic.PacketEvent.alerts)
  return _internal_alerts();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
PacketEvent::mutable_alerts() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:traffic.PacketEvent.alerts)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_alerts();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
PacketEvent::_internal_alerts() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.alerts_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
PacketEvent::_internal_mutable_alerts() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.alerts_;
}

// -------------------------------------------------------------------

// SessionInfo

// string session_id = 1;
inline void SessionInfo::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& SessionInfo::session_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.SessionInfo.session_id)
  return _internal_session_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SessionInfo::set_session_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic.SessionInfo.session_id)
}
inline ::std::string* PROTOBUF_NONNULL SessionInfo::mutable_session_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:traffic.SessionInfo.session_id)
  return _s;
}
inline const ::std::string& SessionInfo::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_.Get();
}
inline void SessionInfo::_internal_set_session_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SessionInfo::_internal_mutable_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SessionInfo::release_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic.SessionInfo.session_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_id_.Set("", GetArena());
  }
  return released;
}
inline void SessionInfo::set_allocated_session_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic.SessionInfo.session_id)
}

// string interface_name = 2;
inline void SessionInfo::clear_interface_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interface_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& SessionInfo::interface_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.SessionInfo.interface_name)
  return _internal_interface_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SessionInfo::set_interface_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.interface_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:traffic.SessionInfo.interface_name)
}
inline ::std::string* PROTOBUF_NONNULL SessionInfo::mutable_interface_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_interface_name();
  // @@protoc_insertion_point(field_mutable:traffic.SessionInfo.interface_name)
  return _s;
}
inline const ::std::string& SessionInfo::_internal_interface_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.interface_name_.Get();
}
inline void SessionInfo::_internal_set_interface_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interface_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SessionInfo::_internal_mutable_interface_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.interface_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SessionInfo::release_interface_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:traffic.SessionInfo.interface_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.interface_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.interface_name_.Set("", GetArena());
  }
  return released;
}
inline void SessionInfo::set_allocated_interface_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.interface_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.interface_name_.IsDefault()) {
    _impl_.interface_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:traffic.SessionInfo.interface_name)
}

// int64 started_unix_ms = 3;
inline void SessionInfo::clear_started_unix_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.started_unix_ms_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t SessionInfo::started_unix_ms() const {
  // @@protoc_insertion_point(field_get:traffic.SessionInfo.started_unix_ms)
  return _internal_started_unix_ms();
}
inline void SessionInfo::set_started_unix_ms(::int64_t value) {
  _internal_set_started_unix_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:traffic.SessionInfo.started_unix_ms)
}
inline ::int64_t SessionInfo::_internal_started_unix_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.started_unix_ms_;
}
inline void SessionInfo::_internal_set_started_unix_ms(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.started_unix_ms_ = value;
}

// -------------------------------------------------------------------

// IngestSummary

// int64 packets_received = 1;
inline void IngestSummary::clear_packets_received() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.packets_received_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::int64_t IngestSummary::packets_received() const {
  // @@protoc_insertion_point(field_get:traffic.IngestSummary.packets_received)
  return _internal_packets_received();
}
inline void IngestSummary::set_packets_received(::int64_t value) {
  _internal_set_packets_received(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:traffic.IngestSummary.packets_received)
}
inline ::int64_t IngestSummary::_internal_packets_received() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.packets_received_;
}
inline void IngestSummary::_internal_set_packets_received(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.packets_received_ = value;
}

// int64 alerts_received = 2;
inline void IngestSummary::clear_alerts_received() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alerts_received_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int64_t IngestSummary::alerts_received() const {
  // @@protoc_insertion_point(field_get:traffic.IngestSummary.alerts_received)
  return _internal_alerts_received();
}
inline void IngestSummary::set_alerts_received(::int64_t value) {
  _internal_set_alerts_received(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:traffic.IngestSummary.alerts_received)
}
inline ::int64_t IngestSummary::_internal_alerts_received() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.alerts_received_;
}
inline void IngestSummary::_internal_set_alerts_received(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alerts_received_ = value;
}

// -------------------------------------------------------------------

// IngestMessage

// .traffic.SessionInfo session_info = 1;
inline bool IngestMessage::has_session_info() const {
  return payload_case() == kSessionInfo;
}
inline bool IngestMessage::_internal_has_session_info() const {
  return payload_case() == kSessionInfo;
}
inline void IngestMessage::set_has_session_info() {
  _impl_._oneof_case_[0] = kSessionInfo;
}
inline void IngestMessage::clear_session_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kSessionInfo) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.session_info_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.session_info_);
    }
    clear_has_payload();
  }
}
inline ::traffic::SessionInfo* PROTOBUF_NULLABLE IngestMessage::release_session_info() {
  // @@protoc_insertion_point(field_release:traffic.IngestMessage.session_info)
  if (payload_case() == kSessionInfo) {
    clear_has_payload();
    auto* temp = _impl_.payload_.session_info_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.session_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::traffic::SessionInfo& IngestMessage::_internal_session_info() const {
  return payload_case() == kSessionInfo ? static_cast<const ::traffic::SessionInfo&>(*_impl_.payload_.session_info_)
                     : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::traffic::SessionInfo>(&::traffic::SessionInfo_globals_);
}
inline const ::traffic::SessionInfo& IngestMessage::session_info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.IngestMessage.session_info)
  return _internal_session_info();
}
inline ::traffic::SessionInfo* PROTOBUF_NULLABLE IngestMessage::unsafe_arena_release_session_info() {
  // @@protoc_insertion_point(field_unsafe_arena_release:traffic.IngestMessage.session_info)
  if (payload_case() == kSessionInfo) {
    clear_has_payload();
    auto* temp = _impl_.payload_.session_info_;
    _impl_.payload_.session_info_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IngestMessage::unsafe_arena_set_allocated_session_info(
    ::traffic::SessionInfo* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_session_info();
    _impl_.payload_.session_info_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:traffic.IngestMessage.session_info)
}
inline ::traffic::SessionInfo* PROTOBUF_NONNULL IngestMessage::_internal_mutable_session_info() {
  if (payload_case() != kSessionInfo) {
    clear_payload();
    set_has_session_info();
    _impl_.payload_.session_info_ = 
        ::google::protobuf::Message::DefaultConstruct<::traffic::SessionInfo>(GetArena());
  }
  return _impl_.payload_.session_info_;
}
inline ::traffic::SessionInfo* PROTOBUF_NONNULL IngestMessage::mutable_session_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::traffic::SessionInfo* _msg = _internal_mutable_session_info();
  // @@protoc_insertion_point(field_mutable:traffic.IngestMessage.session_info)
  return _msg;
}

// .traffic.PacketEvent packet_event = 2;
inline bool IngestMessage::has_packet_event() const {
  return payload_case() == kPacketEvent;
}
inline bool IngestMessage::_internal_has_packet_event() const {
  return payload_case() == kPacketEvent;
}
inline void IngestMessage::set_has_packet_event() {
  _impl_._oneof_case_[0] = kPacketEvent;
}
inline void IngestMessage::clear_packet_event() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kPacketEvent) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.packet_event_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.packet_event_);
    }
    clear_has_payload();
  }
}
inline ::traffic::PacketEvent* PROTOBUF_NULLABLE IngestMessage::release_packet_event() {
  // @@protoc_insertion_point(field_release:traffic.IngestMessage.packet_event)
  if (payload_case() == kPacketEvent) {
    clear_has_payload();
    auto* temp = _impl_.payload_.packet_event_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.packet_event_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::traffic::PacketEvent& IngestMessage::_internal_packet_event() const {
  return payload_case() == kPacketEvent ? static_cast<const ::traffic::PacketEvent&>(*_impl_.payload_.packet_event_)
                     : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::traffic::PacketEvent>(&::traffic::PacketEvent_globals_);
}
inline const ::traffic::PacketEvent& IngestMessage::packet_event() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:traffic.IngestMessage.packet_event)
  return _internal_packet_event();
}
inline ::traffic::PacketEvent* PROTOBUF_NULLABLE IngestMessage::unsafe_arena_release_packet_event() {
  // @@protoc_insertion_point(field_unsafe_arena_release:traffic.IngestMessage.packet_event)
  if (payload_case() == kPacketEvent) {
    clear_has_payload();
    auto* temp = _impl_.payload_.packet_event_;
    _impl_.payload_.packet_event_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IngestMessage::unsafe_arena_set_allocated_packet_event(
    ::traffic::PacketEvent* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_packet_event();
    _impl_.payload_.packet_event_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:traffic.IngestMessage.packet_event)
}
inline ::traffic::PacketEvent* PROTOBUF_NONNULL IngestMessage::_internal_mutable_packet_event() {
  if (payload_case() != kPacketEvent) {
    clear_payload();
    set_has_packet_event();
    _impl_.payload_.packet_event_ = 
        ::google::protobuf::Message::DefaultConstruct<::traffic::PacketEvent>(GetArena());
  }
  return _impl_.payload_.packet_event_;
}
inline ::traffic::PacketEvent* PROTOBUF_NONNULL IngestMessage::mutable_packet_event()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::traffic::PacketEvent* _msg = _internal_mutable_packet_event();
  // @@protoc_insertion_point(field_mutable:traffic.IngestMessage.packet_event)
  return _msg;
}

inline bool IngestMessage::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void IngestMessage::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline IngestMessage::PayloadCase IngestMessage::payload_case() const {
  return IngestMessage::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace traffic


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // packet_5fevent_2eproto_2epb_2eh
